import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import List from "../components/List";
import Map from "../components/Map";
import styled from "styled-components";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <GridContainer>
        <List />
        <Map />
      </GridContainer>
    </div>
  );
};

export default Home;
const Grid = styled.div`
  display: grid;
`;
const GridContainer = styled(Grid)`
  width: 100vw;
  height: 50vh;
  grid-template-columns: 1fr 2fr;
`;
